redshift_lab:
  target: dev
  outputs:
    dev:
      type: redshift
      host: redshift-serverless-workgroup-c35xsydpp79xnt.190440599924.us-east-2.redshift-serverless.amazonaws.com
      port: 5439
      user: admin
      password: "i{Qg1o9x~UdDHSKvFW.S#xY<`~3}->1*e"
      dbname: dev
      schema: public
      threads: 1
      sslmode: prefer
