
version: 2

models:
  - name: clientes
    description: "Clientes tratados com lógica de negócio"
    columns:
      - name: cliente_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
