version: 2

sources:
  - name: raw_data
    schema: raw_data     # ✅ este é o schema onde está a fonte em Redshift
    tables:
      - name: dados_global
        description: Tabela de dados globais brutos

models:
  - name: bronze__dados_global
    description: Modelagem inicial de dados globais
    columns:
      - name: tipo
      - name: cenario
      - name: trimestre
      - name: ano
      - name: preco
