INSERT INTO `silver_terranova.note` (
    header_uuid,
    header_active,
    header_created_at,
    header_updated_at,
    header_date_of_approach,
    header_init_hour,
    header_end_hour,
    header_number_people_approached,
    header_secure_job,
    header_job,
    header_observation,
    header_insecure_conditions,
    header_generate_action_plan,
    header_file,
    header_user,
    header_unity,
    header_administration,
    header_sector,
    value_id,
    value_active,
    value_created_at,
    value_updated_at,
    value_date_of_approach,
    value_number_of_people_in_condition,
    value_description,
    value_options,
    value_critical_task,
    value_aspect,
    value_situation,
    action_plan_id,
    action_plan_active,
    action_plan_created_at,
    action_plan_updated_at,
    action_plan_date_of_approach,
    action_plan_number_of_people_in_condition,
    action_plan_critical,
    action_plan_init_date,
    action_plan_end_date,
    action_plan_reprogram_date,
    action_plan_action,
    action_plan_observation,
    action_plan_file,
    action_plan_finished,
    action_plan_unity,
    action_plan_administration,
    action_plan_sector,
    action_plan_aspect,
    action_plan_situation,
    action_plan_responsible,
    action_plan_status
)
SELECT  
    -- Campos da tabela headers
    headers.uuid AS header_uuid,
    headers.active AS header_active,
    headers.created_at AS header_created_at,
    headers.updated_at AS header_updated_at,
    headers.date_of_approach AS header_date_of_approach,
    headers.init_hour AS header_init_hour,
    headers.end_hour AS header_end_hour,
    headers.number_people_approached AS header_number_people_approached,
    headers.secure_job AS header_secure_job,
    headers.job AS header_job,
    headers.observation AS header_observation,
    headers.insecure_conditions AS header_insecure_conditions,
    headers.generate_action_plan AS header_generate_action_plan,
    headers.file AS header_file,
    headers.user AS header_user,
    headers.unity AS header_unity,
    headers.administration AS header_administration,
    headers.sector AS header_sector,

    -- Campos da tabela values
    values.id AS value_id,
    values.active AS value_active,
    values.created_at AS value_created_at,
    values.updated_at AS value_updated_at,
    values.date_of_approach AS value_date_of_approach,
    values.number_of_people_in_condition AS value_number_of_people_in_condition,
    values.description AS value_description,
    values.options AS value_options,
    values.critical_task AS value_critical_task,
    values.aspect AS value_aspect,
    values.situation AS value_situation,

    -- Campos da tabela action_plan
    action_plan.id AS action_plan_id,
    action_plan.active AS action_plan_active,
    action_plan.created_at AS action_plan_created_at,
    action_plan.updated_at AS action_plan_updated_at,
    action_plan.date_of_approach AS action_plan_date_of_approach,
    action_plan.number_of_people_in_condition AS action_plan_number_of_people_in_condition,
    action_plan.critical AS action_plan_critical,
    action_plan.init_date AS action_plan_init_date,
    action_plan.end_date AS action_plan_end_date,
    action_plan.reprogram_date AS action_plan_reprogram_date,
    action_plan.action AS action_plan_action,
    action_plan.observation AS action_plan_observation,
    action_plan.file AS action_plan_file,
    action_plan.finished AS action_plan_finished,
    action_plan.unity AS action_plan_unity,
    action_plan.administration AS action_plan_administration,
    action_plan.sector AS action_plan_sector,
    action_plan.aspect AS action_plan_aspect,
    action_plan.situation AS action_plan_situation,
    action_plan.responsible AS action_plan_responsible,
    action_plan.status AS action_plan_status
FROM 
    `bronze_terranova.note_headers` AS headers
LEFT JOIN 
    `bronze_terranova.note_values` AS values
ON 
    headers.uuid = values.header_uuid
LEFT JOIN 
    `bronze_terranova.note_action_plan` AS action_plan
ON 
    headers.uuid = action_plan.header_uuid;
